import { Home, Layers, AlertTriangle, Droplets, FlaskConical, ChevronLeft } from "lucide-react";

const NAV = [
  { key: "Overview", icon: Home },
  { key: "Crop Classification", icon: Layers },
  { key: "Stress Detection", icon: AlertTriangle },
  { key: "Irrigation Advisory", icon: Droplets },
  { key: "Simulation Engine", icon: FlaskConical },
];

export default function Sidebar({ active, onSelect, onHome }) {
  return (
    <aside
      data-testid="sidebar"
      className="glass-strong hidden w-64 shrink-0 flex-col justify-between border-r border-white/5 p-5 md:flex"
    >
      <div>
        <button
          data-testid="sidebar-home-button"
          onClick={onHome}
          className="mb-8 flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-white/50 transition hover:text-[#00E65B]"
        >
          <ChevronLeft size={14} strokeWidth={2.4} /> Home
        </button>

        <div className="mb-6 flex items-center gap-2">
          <div className="grid h-9 w-9 place-items-center rounded-lg bg-[#00E65B]/15 ring-1 ring-[#00E65B]/40">
            <span className="font-display text-lg font-bold text-[#00E65B]">K</span>
          </div>
          <div>
            <div className="font-display text-base font-bold leading-none">KrishiDrishti</div>
            <div className="mt-1 text-[10px] uppercase tracking-[0.2em] text-white/45">
              v0.1 · Sim
            </div>
          </div>
        </div>

        <nav className="flex flex-col gap-1">
          {NAV.map(({ key, icon: Icon }) => {
            const isActive = active === key;
            return (
              <button
                key={key}
                data-testid={`nav-${key.toLowerCase().replace(/\s+/g, "-")}`}
                onClick={() => onSelect(key)}
                className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium transition ${
                  isActive
                    ? "bg-[#00E65B]/12 text-[#00E65B] ring-1 ring-[#00E65B]/30"
                    : "text-white/70 hover:bg-white/[0.04] hover:text-white"
                }`}
              >
                <Icon size={16} strokeWidth={2.2} />
                <span>{key}</span>
                {isActive && (
                  <span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#00E65B] pulse-dot" />
                )}
              </button>
            );
          })}
        </nav>
      </div>

      <div className="rounded-xl border border-white/10 bg-white/[0.02] p-3 text-[11px] leading-relaxed text-white/55">
        <span className="text-[#00E5FF]">Synthetic mode.</span> All data is
        generated by a parametric simulator for demo purposes.
      </div>
    </aside>
  );
}
